modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Stalemated/custom-tooltip-api/issues"
license = "MIT"
clientSideOnly = true

[[mods]]
modId = "smart_tooltip_scroll"
version = "${version}"
displayName = "Resized Scrollable Tooltips"
authors = "Stalemated"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "META-INF/icon.jpg"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/custom-tooltip-api"

[[dependencies.smart_tooltip_scroll]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.smart_tooltip_scroll]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.smart_tooltip_scroll]]
modId = "s-lib"
mandatory = true
versionRange = "[0.0.1,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.smart_tooltip_scroll]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[3.6.2,)"
ordering = "AFTER"
side = "CLIENT"
