plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    // StaleLib common code
    modImplementation("com.stalemated.lib:stalelib-fabric:${rootProject.stalelib_version}")

    // YACL
    modImplementation "dev.isxander:yet-another-config-lib:${rootProject.yacl_version}-fabric"
    // ModMenu
    modImplementation "com.terraformersmc:modmenu:${rootProject.modmenu_version}"

    // Legendary Tooltips (compat)
    modCompileOnly "curse.maven:legendary-tooltips-fabric-542478:4940615"
    // Forge Config API Port (compat)
    modCompileOnly "curse.maven:forge-config-api-port-547434:7260491"
    // Prism (compat)
    modCompileOnly "curse.maven:prism-fabric-665526:4650327"
    // Iceberg (compat)
    modCompileOnly "curse.maven:iceberg-fabric-539382:5838145"

    // Tierify (compat)
    modCompileOnly "curse.maven:tierify-974356:5803071"
    // Necronomicon API (compat)
    modCompileOnly "maven.modrinth:necronomicon:1.6.0+1.20.1-fabric"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: inputs.properties.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
