# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.1+26.2
maven_group = com.stalemated.sts
archives_name = smart_tooltip_scroll
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2

# Dependencies
fabric_loader_version = 0.19.3
fabric_api_version = 0.153.0+26.2
neoforge_version=26.2.0.7-beta
s_lib_version = 1.0.2+1.21.1
yacl_version=3.9.5+26.2
modmenu_version=20.0.0
legendary_tooltips_id = 8308375
prism_id = 8308346
iceberg_id = 8308334