architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    mixin {
        defaultRefmapName = "sts-common.refmap.json"
    }
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // S-Lib common code
    modImplementation("com.stalemated.lib:s-lib-common:${rootProject.s_lib_version}")

    // YACL
    modImplementation "dev.isxander:yet-another-config-lib:${rootProject.yacl_version}-fabric"

    // Required to resolve injected Fabric interfaces during compilation (like FabricItemStack)
    modCompileOnly "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    // Legendary Tooltips (IDE Common compat)
    modCompileOnly "curse.maven:legendary-tooltips-fabric-542478:4940615"
    // Iceberg (IDE Common compat)
    modCompileOnly "curse.maven:iceberg-fabric-539382:5838145"
    // Forge Config API Port (compat)
    modCompileOnly "curse.maven:forge-config-api-port-547434:7260491"

    // EMI
    modCompileOnly "dev.emi:emi-xplat-intermediary:${rootProject.emi_version}"

    // Tooltip Overhaul (compat)
    modCompileOnly "curse.maven:tooltip-overhaul-1327508:8380593"

    // Puffish Skills (compat)
    modCompileOnly "curse.maven:puffish-skills-835091:8547669" // 0.18.3
    //modCompileOnly "curse.maven:puffish-skills-835091:7672793" // 0.17.3
    //modCompileOnly "curse.maven:puffish-skills-835091:6540739" // 0.16.0

    // Tierify (compat)
    modCompileOnly "curse.maven:tierify-974356:5803071"
    // Necronomicon API (compat)
    modCompileOnly "maven.modrinth:necronomicon:1.6.0+1.20.1-fabric"

    // Obscure Tooltips (compat)
    modCompileOnly "curse.maven:obscure-tooltips-715660:7568505"
    modCompileOnly "dev.obscuria:fragmentum-api:1.20.1-1.1.0"

    // Spell Engine (compat)
    modCompileOnly "maven.modrinth:spell-engine:0.15.12+1.20.1"
}
